services:
 web:
  image: nginx:latest
  container_name: nginx
  restart: always
  ports:
   - "80:80"
  volumes:
    - ./:/var/www
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
 php:
  build: .
  container_name: php-fpm
  working_dir: /var/www
  volumes:
  - ./:/var/www
  links:
  - db
 db:
  image: mysql:5.7
  container_name: mysql
  ports:
  - "3306:3306"
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: teste