services:
 web:
  image: nginx:latest
  container_name: nginx
  restart: always
  ports:
   - "80:80"
  volumes:
    - ./www:/www
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
 php:
  image: php:8.2-fpm
  container_name: php-fpm
  volumes:
  - ./www:/www